<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class AcmeParqueBundleEntityEspeciesProxy extends \Acme\ParqueBundle\Entity\Especies implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNombrecomun($nombrecomun)
    {
        $this->__load();
        return parent::setNombrecomun($nombrecomun);
    }

    public function getNombrecomun()
    {
        $this->__load();
        return parent::getNombrecomun();
    }

    public function setNombrecientifico($nombrecientifico)
    {
        $this->__load();
        return parent::setNombrecientifico($nombrecientifico);
    }

    public function getNombrecientifico()
    {
        $this->__load();
        return parent::getNombrecientifico();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setFoto($foto)
    {
        $this->__load();
        return parent::setFoto($foto);
    }

    public function getFoto()
    {
        $this->__load();
        return parent::getFoto();
    }

    public function setEstadoconservacion(\Acme\ParqueBundle\Entity\Estadosconservacion $estadoconservacion)
    {
        $this->__load();
        return parent::setEstadoconservacion($estadoconservacion);
    }

    public function getEstadoconservacion()
    {
        $this->__load();
        return parent::getEstadoconservacion();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombrecomun', 'nombrecientifico', 'descripcion', 'foto', 'estadoconservacion');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}