parameters:
#    acme_parque.example.class: Acme\ParqueBundle\Example

services:
#    acme_parque.example:
#        class: %acme_parque.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
